/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Empleados;
import Exepciones.CustomException;
import LogicaNegocio.LogicaEmpleados;
import javax.swing.JOptionPane;
import Servicios.ServicioEmpleado;
import java.io.IOException;
import Presentacion.PatronoVentana.VentanaPatrono;
import Presentacion.EmpleadosVentana.VentanaEmpleado;
/**
 *
 * @author Empresaurio50
 */
public class VentanaLogin extends javax.swing.JFrame {

    private Empleados objEmpleados = new Empleados();
    private ServicioEmpleado servicioEmpledo;
    private VentanaPatrono ventanaPatrono;
    private VentanaEmpleado ventanaEmpleado;
    private VentanaPatrono ventanaPatrono1;
    
    
    

    /**
     * Constructor de la clase VentanaLogin.
     *
     * Inicializa los componentes de la ventana de inicio de sesión, así como
     * las ventanas de patrono y empleado. También intenta inicializar el
     * servicio de empleados y muestra un mensaje de error si ocurre una
     * excepción.
     */
    public VentanaLogin() {
        setTitle("Ventana de Inicio de sesion");
        initComponents(); // Inicializa los componentes de la interfaz gráfica.
        ventanaPatrono = new VentanaPatrono(); // Crea una nueva ventana para el patrono.
        ventanaEmpleado = new VentanaEmpleado(); // Crea una nueva ventana para el empleado.
        try {
            servicioEmpledo = new LogicaEmpleados(); // Intenta inicializar el servicio de empleados.
        } catch (IOException e) {
            // Muestra un cuadro de diálogo con el mensaje de error en caso de excepción.
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        bttLogin = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblCorreo.setText("Correo");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblContra.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblContra.setText("Contraseña");
        jPanel2.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 350, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblTitulo.setText("Iniciar Sesión");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        bttLogin.setBackground(new java.awt.Color(252, 252, 252));
        bttLogin.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bttLogin.setText("Iniciar");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        jPanel2.add(bttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, 40));

        txtContra.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtContra.setBorder(null);
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diseño_sin_título-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 230, 190));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 350, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 350, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("PayManage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 210, 260));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fONDO 2.png"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** * Acción a realizar cuando se pulsa el botón de inicio de sesión. 
     * Este método se encarga de verificar los datos de inicio de sesión del empleado, 
     * y abrir la ventana correspondiente (ventanaPatrono o ventanaEmpleado) dependiendo 
     * del resultado de la verificación. * 
     * @param evt El evento de acción que disparó este método. 
     */
    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed

        objEmpleados = new Empleados();// Crear una nueva instancia de Empleados.

        objEmpleados.setCorreo(txtCorreo.getText());// Establecer el correo del empleado.
        objEmpleados.setPassword(txtContra.getText());// Establecer la contraseña del empleado.
        

        try {
            servicioEmpledo.verificarEmpleado(objEmpleados); // Verificar los datos del empleado.

            // Dependiendo del resultado de la verificación, abrir la ventana correspondiente.
            switch (objEmpleados.getVerificacion()) {
                case 1:
                    ventanaPatrono.setVisible(true);// Mostrar ventana del patrono.
                    ventanaPatrono.setLocationRelativeTo(null);
                    this.setVisible(false);// Ocultar la ventana actual.
                    break;
                case 2:

                    ventanaEmpleado.setVisible(true);// Mostrar ventana del empleado.
                    ventanaEmpleado.setLocationRelativeTo(null);
                    this.setVisible(false);// Ocultar la ventana actual.
                    
                    break;

                default:
                    // Mostrar mensaje de error si el correo o la contraseña son incorrectos.
                    JOptionPane.showMessageDialog(null, "La contrseña o el correo son incorrectos");
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (CustomException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_bttLoginActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
        
        
    }//GEN-LAST:event_txtContraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttLogin;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
