/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Empleados;
import LogicaNegocio.LogicaEmpleados;
import javax.swing.JOptionPane;
import Servicios.ServicioEmpleado;
import java.io.IOException;
import Presentacion.PatronoVentana.VentanaPatrono;
import Presentacion.EmpleadosVentana.VentanaEmpleado;

/**
 *
 * @author Empresaurio50
 */
public class VentanaLogin extends javax.swing.JFrame {

    private Empleados objEmpleados = new Empleados();
    private ServicioEmpleado servicioEmpledo;
    private VentanaPatrono ventanaPatrono;
    private VentanaEmpleado ventanaEmpleado;
    private VentanaPatrono ventanaPatrono1;

    /**
     * Constructor de la clase VentanaLogin.
     *
     * Inicializa los componentes de la ventana de inicio de sesión, así como
     * las ventanas de patrono y empleado. También intenta inicializar el
     * servicio de empleados y muestra un mensaje de error si ocurre una
     * excepción.
     */
    public VentanaLogin() {
        initComponents(); // Inicializa los componentes de la interfaz gráfica.
        ventanaPatrono = new VentanaPatrono(); // Crea una nueva ventana para el patrono.
        ventanaEmpleado = new VentanaEmpleado(); // Crea una nueva ventana para el empleado.
        try {
            servicioEmpledo = new LogicaEmpleados(); // Intenta inicializar el servicio de empleados.
        } catch (IOException e) {
            // Muestra un cuadro de diálogo con el mensaje de error en caso de excepción.
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        bttLogin = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCorreo.setText("Correo");

        lblContra.setText("Contraseña");

        lblTitulo.setText("Iniciar Sesión");

        bttLogin.setText("Iniciar");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblContra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblCorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bttLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtContra)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTitulo)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(58, 58, 58)
                .addComponent(lblCorreo)
                .addGap(18, 18, 18)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblContra)
                .addGap(18, 18, 18)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bttLogin)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** * Acción a realizar cuando se pulsa el botón de inicio de sesión. 
     * Este método se encarga de verificar los datos de inicio de sesión del empleado, 
     * y abrir la ventana correspondiente (ventanaPatrono o ventanaEmpleado) dependiendo 
     * del resultado de la verificación. * 
     * @param evt El evento de acción que disparó este método. 
     */
    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed

        objEmpleados = new Empleados();// Crear una nueva instancia de Empleados.

        objEmpleados.setCorreo(txtCorreo.getText());// Establecer el correo del empleado.
        objEmpleados.setPassword(txtContra.getText());// Establecer la contraseña del empleado.

        try {
            servicioEmpledo.verificarEmpleado(objEmpleados); // Verificar los datos del empleado.

            // Dependiendo del resultado de la verificación, abrir la ventana correspondiente.
            switch (objEmpleados.getVerificacion()) {
                case 1:
                    ventanaPatrono.setVisible(true);// Mostrar ventana del patrono.
                    ventanaPatrono.setLocationRelativeTo(null);
                    this.setVisible(false);// Ocultar la ventana actual.
                    break;
                case 2:

                    ventanaEmpleado.setVisible(true);// Mostrar ventana del empleado.
                    ventanaEmpleado.setLocationRelativeTo(null);
                    this.setVisible(false);// Ocultar la ventana actual.
                    
                    break;

                default:
                    // Mostrar mensaje de error si el correo o la contraseña son incorrectos.
                    JOptionPane.showMessageDialog(null, "La contrseña o el correo son incorrectos");
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_bttLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttLogin;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
