/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.PatronoVentana;

import LogicaNegocio.LogicaEmpleados;
import Servicios.ServicioEmpleado;
import Entidades.Nominas;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import Entidades.Empleados;
import LogicaNegocio.LogicaNominas;
import Servicios.ServicioPatrono;
import com.itextpdf.text.DocumentException;
import Presentacion.VentanaLogin;

/**
 *
 * @author Empresaurio50
 */

public class VentanaPatrono extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPatrono
     */
    private ServicioEmpleado servicioEmpleado;
    private Nominas objNominas;
    private Empleados objEmpleados;
    private VentanaPlantilla ventanaCRUD;
    private VentanaCorreo ventanaCorreo;
    private ServicioPatrono servicioPatrono;
    private VentanaLogin ventanaLogin;

    public VentanaPatrono() {
        try {

            servicioPatrono = new LogicaNominas();
            servicioEmpleado = new LogicaEmpleados();
        } catch (IOException e) {
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpciones = new javax.swing.JLabel();
        bttPlantilla = new javax.swing.JButton();
        bttReporteNomina = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();
        bttAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOpciones.setText("Menu");

        bttPlantilla.setText("Plantilla");
        bttPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPlantillaActionPerformed(evt);
            }
        });

        bttReporteNomina.setText("Reporte Nomina");
        bttReporteNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteNominaActionPerformed(evt);
            }
        });

        bttReportes.setText("Reportes Empleados");
        bttReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReportesActionPerformed(evt);
            }
        });

        bttAtras.setText("Cerrar Session");
        bttAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblOpciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttPlantilla)
                            .addComponent(bttReportes)
                            .addComponent(bttReporteNomina)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bttAtras)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblOpciones)
                .addGap(32, 32, 32)
                .addComponent(bttPlantilla)
                .addGap(71, 71, 71)
                .addComponent(bttReportes)
                .addGap(99, 99, 99)
                .addComponent(bttReporteNomina)
                .addGap(57, 57, 57)
                .addComponent(bttAtras)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPlantillaActionPerformed

        try {
            ventanaCRUD = new VentanaPlantilla();
        } catch (IOException ex) {
            Logger.getLogger(VentanaPatrono.class.getName()).log(Level.SEVERE, null, ex);
        }

        ventanaCRUD.setVisible(true);
        ventanaCRUD.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_bttPlantillaActionPerformed

    private void bttReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReportesActionPerformed

        ventanaCorreo = new VentanaCorreo();

        ventanaCorreo.setVisible(true);
        ventanaCorreo.setLocationRelativeTo(null);
        this.setVisible(false);


    }//GEN-LAST:event_bttReportesActionPerformed

    /** 
     * Acción a realizar cuando se pulsa el botón de reporte de nómina. 
     * Este método se encarga de calcular el total a pagar de las nóminas, 
     * generar un archivo PDF con el reporte de nómina y manejar posibles 
     * excepciones que ocurran durante el proceso. 
     * @param evt El evento de acción que disparó este método. 
     */
    private void bttReporteNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteNominaActionPerformed

        objNominas = new Nominas();
        objEmpleados = new Empleados();

        try {
            servicioEmpleado.leerEmpleado(objEmpleados);

            double totalPagar = 0;
            // Calcula el total a pagar sumando los salarios brutos de todos los empleados.
            for (String[] datosPatrono : objEmpleados.getEmpleadosLista()) {

                totalPagar = totalPagar + Double.parseDouble(datosPatrono[4]);

            }
            objNominas.setTotalPagar(totalPagar);// Establece el total a pagar en el objeto Nominas.

            
            servicioPatrono.crearPDF(objNominas);

        } catch (IOException e) {

            JOptionPane.showMessageDialog(null, "El archivo ya esta creado");
        } catch (DocumentException ex) {
            Logger.getLogger(VentanaPatrono.class.getName()).log(Level.SEVERE, null, ex);
        }
 

    }//GEN-LAST:event_bttReporteNominaActionPerformed

    private void bttAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAtrasActionPerformed
        
        ventanaLogin = new VentanaLogin();
        
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_bttAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new VentanaPatrono().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAtras;
    private javax.swing.JButton bttPlantilla;
    private javax.swing.JButton bttReporteNomina;
    private javax.swing.JButton bttReportes;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
