/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.PatronoVentana;

import Presentacion.PatronoVentana.VentanaCorreo;
import Entidades.Correos;
import Entidades.Empleados;
import LogicaNegocio.LogicaEmpleados;
import Servicios.ServicioEmpleado;
import Entidades.Patrono;
import LogicaNegocio.LogicaCorreos;
import java.io.IOException;
import javax.swing.JOptionPane;
import Servicios.ServicioCorreo;
import com.itextpdf.text.DocumentException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.SendFailedException;


/**
 *
 * @author Empresaurio50
 */
public class VentanaPatrono extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPatrono
     */
    private ServicioEmpleado servicioEmpleado;
    private Patrono objPatrono;
    private VentanaPlantilla ventanaCRUD;
    private VentanaCorreo ventanaCorreo;

    public VentanaPatrono() {
        try {

            servicioEmpleado = new LogicaEmpleados();
        } catch (IOException e) {
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpciones = new javax.swing.JLabel();
        bttPlantilla = new javax.swing.JButton();
        bttPagosTotales = new javax.swing.JButton();
        bttTotalSalarios = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOpciones.setText("Menu");

        bttPlantilla.setText("Plantilla");
        bttPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPlantillaActionPerformed(evt);
            }
        });

        bttPagosTotales.setText("Pagos Plantilla");

        bttTotalSalarios.setText("Total Salario");
        bttTotalSalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttTotalSalariosActionPerformed(evt);
            }
        });

        bttReportes.setText("Reportes Empleados");
        bttReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblOpciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttPlantilla)
                            .addComponent(bttTotalSalarios)
                            .addComponent(bttReportes)
                            .addComponent(bttPagosTotales))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblOpciones)
                .addGap(32, 32, 32)
                .addComponent(bttPlantilla)
                .addGap(40, 40, 40)
                .addComponent(bttReportes)
                .addGap(71, 71, 71)
                .addComponent(bttPagosTotales)
                .addGap(62, 62, 62)
                .addComponent(bttTotalSalarios)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttTotalSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttTotalSalariosActionPerformed

        objPatrono = new Patrono();

        try {
            servicioEmpleado.leerEmpleado(objPatrono);

            double totalPagar = 0;
            for (String[] datosPatrono : objPatrono.getEmpleadosLista()) {

                totalPagar = totalPagar + Double.parseDouble(datosPatrono[4]);

            }
            JOptionPane.showMessageDialog(null, "Total a pagar " + totalPagar);
            objPatrono.setTotalPagar(totalPagar);
        } catch (IOException e) {

            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }


    }//GEN-LAST:event_bttTotalSalariosActionPerformed

    private void bttPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPlantillaActionPerformed
        
        try {
            ventanaCRUD = new VentanaPlantilla();
        } catch (IOException ex) {
            Logger.getLogger(VentanaPatrono.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ventanaCRUD.setVisible(true);
        ventanaCRUD.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_bttPlantillaActionPerformed

    private void bttReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReportesActionPerformed
        
        ventanaCorreo = new VentanaCorreo();
        
        ventanaCorreo.setVisible(true);
        ventanaCorreo.setLocationRelativeTo(null);
        this.setVisible(false);
        
       
    }//GEN-LAST:event_bttReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPatrono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttPagosTotales;
    private javax.swing.JButton bttPlantilla;
    private javax.swing.JButton bttReportes;
    private javax.swing.JButton bttTotalSalarios;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
