/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.EmpleadosVentana;
import Presentacion.VentanaLogin;
/**
 *
 * @author Empresaurio50
 */
public class VentanaEmpleado extends javax.swing.JFrame {

    private VentanaMirarPlantilla ventanaMirarPlantilla;
    private VentanaCorreosEmpleados ventanaCorreosEmpleados;
    private  VentanaLogin ventanaLogin;
    
    /**
     * Creates new form VentanaEmpleado
     */
    public VentanaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOpciones = new javax.swing.JLabel();
        bttCerrarSeccion = new javax.swing.JButton();
        bttMirarPlantilla = new javax.swing.JButton();
        bttCorreoEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOpciones.setText("Opciones Del Empleado");

        bttCerrarSeccion.setText("Salir");
        bttCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarSeccionActionPerformed(evt);
            }
        });

        bttMirarPlantilla.setText("Plantilla");
        bttMirarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMirarPlantillaActionPerformed(evt);
            }
        });

        bttCorreoEmpleado.setText("Correos");
        bttCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCorreoEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblOpciones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttCerrarSeccion)
                            .addComponent(bttMirarPlantilla)
                            .addComponent(bttCorreoEmpleado))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblOpciones)
                .addGap(58, 58, 58)
                .addComponent(bttMirarPlantilla)
                .addGap(76, 76, 76)
                .addComponent(bttCorreoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(bttCerrarSeccion)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttMirarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMirarPlantillaActionPerformed
        
        ventanaMirarPlantilla = new VentanaMirarPlantilla();
        
        ventanaMirarPlantilla.setVisible(true);
        ventanaMirarPlantilla.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_bttMirarPlantillaActionPerformed

    private void bttCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCorreoEmpleadoActionPerformed
        ventanaCorreosEmpleados = new VentanaCorreosEmpleados();
        
        ventanaCorreosEmpleados.setVisible(true);
        ventanaCorreosEmpleados.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_bttCorreoEmpleadoActionPerformed

    private void bttCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarSeccionActionPerformed
        
        ventanaLogin = new VentanaLogin();
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_bttCerrarSeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCerrarSeccion;
    private javax.swing.JButton bttCorreoEmpleado;
    private javax.swing.JButton bttMirarPlantilla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
