/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.EmpleadosVentana;
import Presentacion.VentanaLogin;
/**
 *
 * @author Empresaurio50
 */
public class VentanaEmpleado extends javax.swing.JFrame {

    private VentanaMirarPlantilla ventanaMirarPlantilla;
    private VentanaCorreosEmpleados ventanaCorreosEmpleados;
    private  VentanaLogin ventanaLogin;
    
    /**
     * Creates new form VentanaEmpleado
     */
    public VentanaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        lblOpciones = new javax.swing.JLabel();
        bttCerrarSeccion = new javax.swing.JButton();
        bttMirarPlantilla = new javax.swing.JButton();
        bttCorreoEmpleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpciones.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblOpciones.setText("Menu Del Empleado");
        jPanel2.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        bttCerrarSeccion.setBackground(new java.awt.Color(252, 252, 252));
        bttCerrarSeccion.setText("Salir");
        bttCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarSeccionActionPerformed(evt);
            }
        });
        jPanel2.add(bttCerrarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 100, 40));

        bttMirarPlantilla.setBackground(new java.awt.Color(252, 252, 252));
        bttMirarPlantilla.setText("Plantilla");
        bttMirarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMirarPlantillaActionPerformed(evt);
            }
        });
        jPanel2.add(bttMirarPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, 40));

        bttCorreoEmpleado.setBackground(new java.awt.Color(252, 252, 252));
        bttCorreoEmpleado.setText("Correos");
        bttCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCorreoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(bttCorreoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fONDO 2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 70, -1, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prueba 2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * Acción a realizar cuando se pulsa el botón de mirar plantilla.
     * Este método se encarga de crear y mostrar la ventana de mirar plantilla,
     * y ocultar la ventana actual. * * @param evt El evento de acción que disparó este método. 
     */
    private void bttMirarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMirarPlantillaActionPerformed
        
        ventanaMirarPlantilla = new VentanaMirarPlantilla();// Crea una nueva instancia de la ventana de mirar plantilla.
        
        ventanaMirarPlantilla.setVisible(true); // Hace visible la ventana de mirar plantilla.
        ventanaMirarPlantilla.setLocationRelativeTo(null);// Centra la ventana de mirar plantilla en la pantalla.
        
        this.setVisible(false);// Oculta la ventana actual.
        
    }//GEN-LAST:event_bttMirarPlantillaActionPerformed

    /** 
     * Acción a realizar cuando se pulsa el botón de correo a empleado. 
     * Este método se encarga de crear y mostrar la ventana de correos a empleados, 
     * y ocultar la ventana actual. 
     * @param evt El evento de acción que disparó este método. 
     */
    
    private void bttCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCorreoEmpleadoActionPerformed
        ventanaCorreosEmpleados = new VentanaCorreosEmpleados();// Crea una nueva instancia de la ventana de correos a empleados.
        
        ventanaCorreosEmpleados.setVisible(true);// Hace visible la ventana de correos a empleados.
        ventanaCorreosEmpleados.setLocationRelativeTo(null);// Centra la ventana de correos a empleados en la pantalla.
        this.setVisible(false);// Oculta la ventana actual.
        
    }//GEN-LAST:event_bttCorreoEmpleadoActionPerformed

    /** 
     * Acción a realizar cuando se pulsa el botón de cerrar sesión. 
     * Este método se encarga de crear y mostrar la ventana de inicio de sesión, 
     * y ocultar la ventana actual. 
     *  @param evt El evento de acción que disparó este método. 
     */
    private void bttCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarSeccionActionPerformed
        
        ventanaLogin = new VentanaLogin();// Crea una nueva instancia de la ventana de inicio de sesión.
        ventanaLogin.setVisible(true);// Hace visible la ventana de inicio de sesión.
        ventanaLogin.setLocationRelativeTo(null);// Centra la ventana de inicio de sesión en la pantalla.
        
        this.setVisible(false);// Oculta la ventana actual.
    }//GEN-LAST:event_bttCerrarSeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCerrarSeccion;
    private javax.swing.JButton bttCorreoEmpleado;
    private javax.swing.JButton bttMirarPlantilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
